services:
  learn-play:
    container_name: learn-play
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_PORT}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    networks:
      - ogdenor

networks:
  ogdenor:
    external: true
